const din = "دين";

final arabicFonts = [
  "Default",
  "Aref Ruqaa",
  "Amiri",
  "Almarai",
  "Cairo",
  "Changa",
  //"Gulzar",
  "Harmattan",
  "IBM Plex Sans Arabic",
  "Katibeh",
  "Lemonada",
  "Lateef",
  "Mada",
  "Markazi Text",
  "Mirza",
  "Noto Naskh Arabic",
  "Noto Sans Arabic",
  "Noto Nastaliq Urdu",
  "Noto Kufi Arabic",
  "Qahiri",
  "Rakkas",
  "Reem Kufi",
  "Scheherazade New",
  "Tajawal",
  "Vazirmatn",
  "Vibes",
];
